export const GET_DEMURRAGE_CALCULATON = 'GET_DEMURRAGE_CALCULATON';
export const GET_DEMURRAGE_CALCULATON_SUCCESS = 'GET_DEMURRAGE_CALCULATON_SUCCESS';
export const GET_DEMURRAGE_CALCULATON_ERROR = 'GET_DEMURRAGE_CALCULATON_ERROR';