/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:7224d1cc-256a-43be-8161-f83b260bc691",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_o8KItBFfm",
    "aws_user_pools_web_client_id": "67d4f74h940k66e2e5henbrqtg",
    "oauth": {}
};


export default awsmobile;
