export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';
export const SAVE_EMPLOYEE_SUCCESS = 'SAVE_EMPLOYEE_SUCCESS';
export const SAVE_EMPLOYEE_ERROR = 'SAVE_EMPLOYEE_ERROR';

export const VIEW_EMPLOYEE = 'VIEW_EMPLOYEE';
export const VIEW_EMPLOYEE_SUCCESS = 'VIEW_EMPLOYEE_SUCCESS';
export const VIEW_EMPLOYEE_ERROR = 'VIEW_EMPLOYEE_ERROR';

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR';

export const VIEW_EMPLOYEE_BY_ID = 'VIEW_EMPLOYEE_BY_ID';
export const VIEW_EMPLOYEE_BY_ID_SUCCESS = 'VIEW_EMPLOYEE_BY_ID_SUCCESS';
export const VIEW_EMPLOYEE_BY_ID_ERROR = 'VIEW_EMPLOYEE_BY_ID_ERROR';

export const CLEAR_EMPLOYEE_DETAILS = 'CLEAR_EMPLOYEE_DETAILS';