export const FETCH_ACTIVITY_LIST = 'FETCH_ACTIVITY_LIST';
export const FETCH_ACTIVITY_LIST_SUCCESS = 'FETCH_ACTIVITY_LIST_SUCCESS';
export const FETCH_ACTIVITY_LIST_ERROR = 'FETCH_ACTIVITY_LIST_ERROR';

export const FETCH_ACTIVITY_LOGS = 'FETCH_ACTIVITY_LOGS';
export const FETCH_ACTIVITY_LOGS_SUCCESS = 'FETCH_ACTIVITY_LOGS_SUCCESS';
export const FETCH_ACTIVITY_LOGS_ERROR = 'FETCH_ACTIVITY_LOGS_ERROR';

export const FETCH_ACTIVITY_LOGS_TYPES = 'FETCH_ACTIVITY_LOGS_TYPES';
export const FETCH_ACTIVITY_LOGS_TYPES_SUCCESS = 'FETCH_ACTIVITY_LOGS_TYPES_SUCCESS';
export const FETCH_ACTIVITY_LOGS_TYPES_ERROR = 'FETCH_ACTIVITY_LOGS_TYPES_ERROR';

export const SAVE_ACTIVITY_LOGS_TYPES = 'SAVE_ACTIVITY_LOGS_TYPES';
export const SAVE_ACTIVITY_LOGS_TYPES_SUCCESS = 'SAVE_ACTIVITY_LOGS_TYPES_SUCCESS';
export const SAVE_ACTIVITY_LOGS_TYPES_ERROR = 'SAVE_ACTIVITY_LOGS_TYPES_ERROR';

export const FETCH_ACTIVITY_EVENT_TYPES = 'FETCH_ACTIVITY_EVENT_TYPES';
export const FETCH_ACTIVITY_EVENT_TYPES_SUCCESS = 'FETCH_ACTIVITY_EVENT_TYPES_SUCCESS';
export const FETCH_ACTIVITY_EVENT_TYPES_ERROR = 'FETCH_ACTIVITY_EVENT_TYPES_ERROR';