export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';
export const SAVE_EMPLOYEE_SUCCESS = 'SAVE_EMPLOYEE_SUCCESS';
export const SAVE_EMPLOYEE_ERROR = 'SAVE_EMPLOYEE_ERROR';

export const VIEW_EMPLOYEE = 'VIEW_EMPLOYEE';
export const VIEW_EMPLOYEE_SUCCESS = 'VIEW_EMPLOYEE_SUCCESS';
export const VIEW_EMPLOYEE_ERROR = 'VIEW_EMPLOYEE_ERROR';