export const WARE_HOUSE_DETALS_SAVE = 'WARE_HOUSE_DETALS_SAVE';
export const WARE_HOUSE_DETALS_SAVE_SUCCESS = 'WARE_HOUSE_DETALS_SAVE_SUCCESS';
export const WARE_HOUSE_DETALS_SAVE_ERROR = 'WARE_HOUSE_DETALS_SAVE_ERROR';

export const VIEW_WARE_HOUSE_DETALS = 'VIEW_WARE_HOUSE_DETALS';
export const VIEW_WARE_HOUSE_DETALS_SUCCESS = 'VIEW_WARE_HOUSE_DETALS_SUCCESS';
export const VIEW_WARE_HOUSE_DETALS_ERROR = 'VIEW_WARE_HOUSE_DETALS_ERROR';